name       : budgie-calendar-applet
version    : 5.2
release    : 3
source     :
    - https://github.com/danielpinto8zz6/budgie-calendar-applet/archive/5.2.tar.gz : ce7c3d88dbdfd5026ce530c2c6647c7432dd51c4541c5d5fed7a08604383fb24
license    : GPL-2.0-or-later
component  : desktop.budgie
summary    : Calendar applet for the Budgie Desktop
description: |
    A budgie-desktop applet to show hours and when click show a calendar in a popover
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
