name       : budgie-calendar-applet
version    : 4.1
release    : 2
source     :
    - https://github.com/danielpinto8zz6/budgie-calendar-applet/archive/4.1.tar.gz : d735fc0ebf7c50b0cee1498da2b7fe9a51eac5c115264605c4035d58cb5bc98b
license    : GPL-2.0-or-later
component  : desktop.budgie
summary    : Calendar applet for the Budgie Desktop
description: |
    A budgie-desktop applet to show hours and when click show a calendar in a popover
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
