name       : budgie-calendar-applet
version    : 4.0
release    : 1
source     :
    - https://github.com/danielpinto8zz6/budgie-calendar-applet/archive/4.0.tar.gz : a0bc635ba86568b44cf84450877b7a05462ebb7d5e13ed99af48950011f70a74
license    : GPL-2.0
component  : desktop.budgie
summary    : Calendar applet for the Budgie Desktop
description: |
    A budgie-desktop applet to show hours and when click show a calendar in a popover
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
