name       : budgie-calendar-applet
version    : 5.2
release    : 4
source     :
    - git|https://github.com/danielpinto8zz6/budgie-calendar-applet : b3b8caaf9379afc93f64bf338861fe6392100fbc
homepage   : https://github.com/danielpinto8zz6/budgie-calendar-applet
license    : GPL-2.0-or-later
component  : desktop.budgie
summary    : Calendar applet for the Budgie Desktop
description: |
    A budgie-desktop applet to show hours and when click show a calendar in a popover.
builddeps  :
    - pkgconfig(budgie-1.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
